[package]
name = "toycc_argparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.1"
toycc_report = {path = "../toycc_report"}
colored = "2.1.0"